config/routes.rb
Rails.application.routes.draw do  
  resources :recipe_ingredients
  resources :comments, only: [:destroy, :new, :update]
  resources :users do
    resources :recipes
  end
  resources :instructions
  resources :ingredients
  root to: 'static#home'
  
  resources :recipes do
    resources :comments
  end
    
  resources :categories do
      resources :recipes
  end


  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'destroy_user_session'
  
  
  # match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get,:post]
  # match '/auth/:google_oauth2/callback' => 'sessions#omniauth', via: [:get, :post]

  # get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  match '/auth/:google_oauth2/callback' => 'sessions#omniauth', via: [:get, :post]

  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :comment_auth, only: [:edit, :update, :destroy]
  
  def new 
    @comment = Comment.new
  end

  def show
    comment = Comment.find_by(user: current_user, recipe: find_by_recipe_id)
  end

  def create
      comment = Comment.new(comment_params)
      comment.recipe = find_by_recipe_id(@recipe)
      
      if comment.user_id = current_user.id
        comment.save
        flash[:notice] = "Comment has been added."
        redirect_to recipe_path(comment.recipe)
      else
        flash[:notice] = "You must be logged in to post a comment."
        redirect_to recipe_path
      end
  end

  def edit  
  end

  def update
    if @comment.user_id = current_user.id
      @comment.update(comment_params)      
      redirect_to recipe_path(@comment.recipe)
      flash.now[:notice] = "Your comment has been updated."
    else
      redirect_to recipe_path
      flash.now[:notice] = "You cannot update this comment."
    end
    
  end

  def destroy
    if @comment.user_id == current_user.id 
    @comment.destroy
    flash[:notice] = "The comment was deleted."
    redirect_to recipe_path
    else
    flash[:notice] = "You must be comment owner to delete comment."
    redirect_to recipe_path
    end
  end


  private

  def comment_auth
    @comment = find_comment
    if @comment.user_id != current_user.id
      flash[:notice] = "You must be comment owner to update comment."
      redirect_to recipe_path(@comment.recipe)
    end
  end

  def comment_params
    #do i need to add permission for recipe_id & user_id?
    params.require(:comment).permit(:content)
  end

  def find_comment
    @comment = Comment.find_by_id(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments_list.html.erb
<% comments.each do |comment| %>
<div>
<!--do i need additional logic here re: current_user-->
  <p><%= link_to comment.user.name, user_path(comment.user) %> says: <%= link_to comment.content, edit_recipe_comment_path(recipe, comment) %> </p>
</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [recipe, comment] do |f| %>
  <div>
    <p>Comment: <%= f.text_area :content %></p>
    <%= f.submit button_name:"Add Comment", class: "custom_button"%>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render partial: "form", locals: {comment: @comment, recipe: @comment.recipe, button_name: "Update Comment"} %> 
<br>

<%= link_to "Delete Comment", comment_path(@comment), method: "delete", class:"custom_button"%> 

app/views/comments/new.html.erb
<%= render partial: "form", locals: {comment: @comment, recipe: @comment.recipe, button_name: "Add Comment"} %>