config/routes.rb
Rails.application.routes.draw do  
  resources :recipe_ingredients
  resources :comments, only: [:destroy, :new, :update]
  resources :users do
    resources :recipes
  end
  resources :instructions
  resources :ingredients
  root to: 'static#home'
  
  resources :recipes do
    resources :comments
  end
    
  resources :categories do
      resources :recipes
  end


  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'destroy_user_session'
  
  
  # match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get,:post]
  # match '/auth/:google_oauth2/callback' => 'sessions#omniauth', via: [:get, :post]

  # get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  match '/auth/:google_oauth2/callback' => 'sessions#omniauth', via: [:get, :post]

  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  accepts_nested_attributes_for :category, reject_if: :all_blank
  has_many :users, through: :categories  
  has_many :ingredients, dependent: :destroy
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: :true
  has_many :instructions, dependent: :destroy
  accepts_nested_attributes_for :instructions, reject_if: :all_blank, allow_destroy: :true
  has_many :comments
  validates :title, presence: true, uniqueness: true

  # def categories_attributes=(categories_attributes)
  #   categories_attributes.each do |i, category_attributes| 
  #   self.categories.build(category_attributes)
  #   end
  # end

  def self.alphabetize
    order(title: :asc)
  end

  def category_attributes=(hash_of_attributes)
    if !hash_of_attributes[:name].blank? 
        self.category = Category.find_or_create_by(hash_of_attributes)
    end
  end

  def category_name
    self.category ? self.category.name : "Category not available"
  end  

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :find_category, only: [:index, :new, :create]
  before_action :redirect_if_not_logged_in
  before_action :redirect_if_not_owner, only: [:edit, :update, :destroy]

  def index
    if @category 
      @recipes = @category.recipes
    else
      @recipes = Recipe.all
    end
  end

  def new
    if @category 
      @recipe = @category.recipes.build 
      render :new_category_recipe
    else
    @recipe = Recipe.new
    end
  end

  def create
    params[:recipe][:user_id] = current_user.id
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      if @category
        redirect_to category_recipes_path(@category) 
      else
        redirect_to recipes_path
      end
    else
      flash.now[:error] = @recipe.errors.full_messages
      if @category 
        render :new_category_recipe
      else
        render :new
      end
    end
  end

  def show
    if @category
      redirect_to category_recipe_path(@category) 
    end
    if @comment
      redirect_to recipe_path(@recipe)
    end
  end

  def edit

  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      flash.now[:error] = @recipe.errors.full_messages
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    flash[:notice] = "#{@recipe.title} was deleted."
    redirect_to recipes_path
  end

  
  private
  
  def find_recipe
    @recipe = Recipe.find_by_id(params[:id])
  end

  def find_category
    if params[:category_id]
      @category = Category.find_by_id(params[:category_id])
    end
  end

  def redirect_if_not_owner
    flash[:notice] = "You cannot delete or update a recipe if you are not the owner."
    return redirect_to recipes_path unless @recipe 
    redirect_to recipes_path unless current_user.id == @recipe.user_id
  end  

  def recipe_params
    params.require(:recipe).permit(
      :title, 
      :category_id,
      :user_id,
      :description, 
      :ingredient, 
      :instructions, 
      category_attributes: [:name, :user_id],
      ingredients_attributes: [:id, :ingredient_name],
      instructions_attributes: [:id, :step]
    )
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for [@category, @recipe] do |f| %>
 <%= f.hidden_field :user_id, value:current_user.id %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

   
    <h5>Add Instructions</h5>
    <div style="margin-left:30px">
      <%= f.fields_for :instructions do |instruction| %>
      <%= render 'instruction_fields', f: instruction %>
      <% end %>
      <div class="links">
      <%= link_to_add_association 'Add Step', f, :instructions %>
      </div>
    </div>


    <h5>Select Category</h5>
      <div style="margin-left:30px">
        <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "Select Category" %>    
      </div>

    <h5>Create Category</h5>
      <%= f.fields_for :category, recipe.build_category do |cb| %>
      <div style="margin-left:30px">
        <%= cb.label :name %>
        <%= cb.text_field :name %>
        <%= cb.hidden_field :user_id, value:current_user.id %>
      </div>
      <% end %>

  <%= f.submit button_name, class: "custom_button"%>
<% end %>

<script>$(document).ready(function(){
    $('select').formSelect();
  });</script>

app/views/recipes/_instruction_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :step %>
    <%= f.text_field :step %>
    <%= link_to_remove_association 'Delete Step', f %>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<p><%= link_to(recipe.title, recipe_path(recipe.id)) %></p>

app/views/recipes/edit.html.erb
<h3>Edit <%= @recipe.title %></h3>

<%= render partial: "form", locals: {recipe: @recipe, button_name: "Update Recipe"}%>

app/views/recipes/index.html.erb
<h3>All <%= @category.name if @category%> Recipes </h3>
<ul>
  <%@recipes.each do |recipe| %>
  <li><%= link_to recipe.title, recipe_path(recipe) %></li>
  
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h3>Create Recipe</h3>

<%= render partial: "form", locals: {recipe: @recipe, user: current_user, button_name: "Create Recipe"} %>


<script>$(document).ready(function(){
    $('select').formSelect();
  });</script>

app/views/recipes/new_category_recipe.html.erb
<h3>Create Recipe</h3>

<%= render partial: "form", locals: {recipe: @recipe, category: @category,  button_name: "Create Recipe"} %>


<script>$(document).ready(function(){
    $('select').formSelect();
  });</script>

app/views/recipes/show.html.erb
<h4><%= @recipe.title %></h4>
<div class="container" style="margin-left:35px;">

<h5 style="font-size:1.45rem"> ● Category:</h5>
  <ul>
  
    <li style="margin-left:20px;"><%= link_to @recipe.category_name, category_path(@recipe.category_id) %></li>
  </ul>

<h5 style="font-size:1.45rem">● Description:</h5>
  <ul>
    <li style="margin-left:20px;"><%= @recipe.description %></li>
  </ul>

<h5 style="font-size:1.45rem">● Ingredients:</h5>
 

<h5 style="font-size:1.45rem">● Instructions:</h5>
    <ol>
      <% for @instruction in @recipe.instructions %>
        <li><%= @instruction.step %></li>
        <% end %>    
    </ol>
<br>

<!-- This is where my problem is with the create comment button not refreshing show page -->
<h5 style="font-size:1.45rem">● Recipe Comments:</h5>
<div style="margin-left:25px;">
  <%= render partial: 'comments/comments_list', locals: {comments: @recipe.comments, recipe: @recipe} if @recipe.comments %>
  
</div>
<br>


  <h5>Add Recipe Comments:</h5>
    <%= render 'comments/form', comment: @recipe.comments.new, recipe: @recipe %>   

  <br>
  <br>


<div>
<%= link_to "Edit Recipe", edit_recipe_path(@recipe), class:"custom_button" %>
<%= link_to "Delete Recipe", recipe_path(@recipe), method: "delete", class:"custom_button"%>
</div>