config/routes.rb
Rails.application.routes.draw do  
  resources :recipe_ingredients
  resources :comments, only: [:destroy, :new, :update]
  resources :users do
    resources :recipes
  end
  resources :instructions
  resources :ingredients
  root to: 'static#home'
  
  resources :recipes do
    resources :comments
  end
    
  resources :categories do
      resources :recipes
  end


  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'destroy_user_session'
  
  
  # match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get,:post]
  # match '/auth/:google_oauth2/callback' => 'sessions#omniauth', via: [:get, :post]

  # get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  match '/auth/:google_oauth2/callback' => 'sessions#omniauth', via: [:get, :post]

  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :users
  has_many :recipes
  accepts_nested_attributes_for :recipes, reject_if: :all_blank

  validates :name, presence: true, uniqueness: true

  def self.alphabetize
    order(name: :asc)
  end
  # def recipes_attributes=(recipes_attributes)
  #   recipes_attributes.each do |i, recipe_attributes| 
  #   self.recipes.build(recipe_attributes)
  #   end
  # end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :find_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all.alphabetize
  end

  def new
    @category = Category.new

    @category.recipes.build

  end

  def create
    params[:category][:user_id] = current_user.id
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      flash.now[:error] = @category.errors.full_messages
      render :new
    end
  end

  def show
    @category = Category.find_by_id(params[:id])
  end

  def edit
    
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      flash.now[:error] = @category.errors.full_messages
      render :edit
    end
  end

  def destroy
    # if @category
    @category.destroy
    flash[:notice] = "#{@category.name} was deleted."
    redirect_to category_path
    # elsif @category.recipe
    #   flash[:notice] = "#{@category.name} is associated with an existing recipe and cannot be deleted."
    # end
  end

  private

  def find_category
    @category = Category.find_by_id(params[:id])
  end
  
  def category_params
    params.require(:category).permit(
      :name, 
      :user_id, 
      recipes_attributes: [:title, :description], 
      ingredients_attributes: [:id, :ingredient_name],
      instructions_attributes: [:id, :step]
      )
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h3>Edit <%= @category.name %></h3>


    <%= form_for [@category] do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.hidden_field :user_id, value:current_user.id %>
    </div>

    <%= f.submit button_name:"Update Category", class: "custom_button"%>
    <% end %>

app/views/categories/index.html.erb
<h3>All Categories</h3>

<ul>
  <% @categories.each do |category| %>
  <li style="list-style-type: disc;"> <%= link_to category.name, category_path(category) %></li>
<% end %>
</ul>

app/views/categories/new.html.erb
<h3>Create Category</h3>

<%= form_for @category do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div> 
    
    <%= f.submit "Create Category", class:"custom_button" %>
  <% end %>
  <br>


  <%= link_to "Create Recipe with Category", new_category_recipe_path(@category.recipes), class: "custom_button" %>

app/views/categories/show.html.erb
<h3>All Recipes for <%= @category.name %> </h3>

<ul>
  <li><%= render @category.recipes  %> </li>
</ul>
<br>

<%= link_to "Edit Category Name", edit_category_path(@category), class:"custom_button" %> &nbsp;

<%= link_to "Create New Recipe for #{@category.name}", new_category_recipe_path(@category), class: "custom_button" %>

<%# <%= link_to "Delete Category Name", category_path(@category), method: "delete", class:"custom_button"%> 