config/routes.rb
Rails.application.routes.draw do  
  resources :recipe_ingredients
  resources :comments, only: [:destroy, :new, :update]
  resources :users do
    resources :recipes
  end
  resources :instructions
  resources :ingredients
  root to: 'static#home'
  
  resources :recipes do
    resources :comments
  end
    
  resources :categories do
      resources :recipes
  end


  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: 'destroy_user_session'
  
  
  # match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get,:post]
  # match '/auth/:google_oauth2/callback' => 'sessions#omniauth', via: [:get, :post]

  # get 'auth/google_oauth2/callback', to: 'sessions#omniauth'
  match '/auth/:google_oauth2/callback' => 'sessions#omniauth', via: [:get, :post]

  
end

app/views/layouts/_errors.html.erb
<div class="container">
  <div class="fields_with_errors">
  <% if flash[:error] %>
    <% flash[:error].each do |error| %>
      <p><%= error %> </p>
      <% end %>
    <% end %>


    <%= content_tag("p", flash[:notice]) if flash[:notice] %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav style="background-color: #006a71;">
<% if user_signed_in? %>
  <ul id="dropdown1" class="dropdown-content">
    <li><%= link_to 'All Recipes', recipes_path%></li>
    <!-- recipe_myrecipes_path -->
    <li><%= link_to 'My Recipes', user_path(current_user.id) %></li>
    <li><%= link_to 'Create Recipe', new_recipe_path %></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %></li>
  </ul>
  <ul id="dropdown3" class="dropdown-content">
    <li><%= link_to 'Category List', categories_path %></li>
    <li><%= link_to 'Create Category', new_category_path %></li>
  </ul>
  <% else %>
  <ul id="dropdown4" class="dropdown-content">
    <li><%= link_to 'Login', login_path %></li>
    <li><%= link_to 'Log In With Google', '/auth/google_oauth2', method: :post %></li>
    <li><%= link_to 'Create New Account', signup_path %></li>
  </ul>

<% end %>

  </ul>
    <div class="nav-wrapper container" >
      <a href="/" class="brand-logo left" style="font-family: 'Sacramento', cursive; font-size:55px; padding-top:7px;">Taste</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">      
        
        <% if user_signed_in? %>
        <li><a href="#">Hi, &nbsp; <%= current_user.name %></a></li>
        <li><%= link_to 'Home', root_path%></li>
         <li><a class="dropdown-trigger" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
         <li><a class="dropdown-trigger" data-target="dropdown1">Recipes<i class="material-icons right">arrow_drop_down</i></a></li>
         <li><a class="dropdown-trigger" data-target="dropdown3">Categories<i class="material-icons right">arrow_drop_down</i></a></li>
         <% else %>
         <li><%= link_to 'Home', root_path%></li>
         <li><a class="dropdown-trigger" data-target="dropdown4">Account<i class="material-icons right">arrow_drop_down</i></a></li>
      </ul>
    <% end %>
    </div>

  </nav>

<script>
$(document).ready(function(){
  $(".dropdown-trigger").dropdown();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Stylesheets -->
    <link rel="stylesheet" href="/stylesheets/main.css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&family=Montserrat:wght@300&family=Sacramento&display=swap" rel="stylesheet">

        <!-- Google Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Materialize -->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

            
  </head>

  <body>
    <%= render partial: 'layouts/nav'  %>
    <%= render 'layouts/errors' %>

  <div class="container">
    <%= yield %>  
  </div>
  </body>
</html>

app/views/layouts/home_page_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Stylesheets -->
    <link rel="stylesheet" href="/stylesheets/main.css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&family=Montserrat:wght@300&family=Sacramento&display=swap" rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
  </head>

  <body>
    <div class="container">
      <%= yield %>  
      
      <% if !user_signed_in? %>
      <ul>
        <li><%= link_to "Recipes", recipes_path, class:"custom_button" %></li>
        <br>
        <li><%= link_to "Signup", signup_path, class:"custom_button"%></li>
        <br>
        <li><%= link_to "Login", login_path, class:"custom_button"%></li>
        <br>
        <li><%= link_to 'Log In With Google', '/auth/google_oauth2', method: :post, class:"custom_button"%></li>
        <br>
      </ul>
      <% else %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: 'DELETE', class:"custom_button" %></li>
        <br>
        <li><%= link_to 'Back to Recipes', recipes_path, class: "custom_button" %> </li>
    </div>
     <% end %>
  </body>
</html>